# Netlify 빌드 및 배포 설정
[build]
  # API 함수가 사용하는 @google/generative-ai 패키지를 설치하기 위한 명령어입니다.
  command = "npm install"
  
  # 배포할 폴더입니다. index.html이 루트에 있으므로 '.'으로 설정합니다.
  publish = "."

# Netlify 함수(API) 설정
[functions]
  # Vercel처럼 'api' 폴더를 함수 폴더로 사용하도록 Netlify에 알려줍니다.
  directory = "api"

# URL 재작성 규칙 (프론트엔드 코드 수정을 막아주는 핵심 설정)
# index.html에서 '/api/generate-questions'로 보내는 요청을
# 실제 Netlify 함수 주소인 '/.netlify/functions/generate-questions'로 연결해줍니다.
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
